# Generated by Django 5.0 on 2023-12-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_glucosereading_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='glucosereading',
            name='reading_type',
            field=models.CharField(choices=[('before', 'Before Eating'), ('after', 'After Eating')], default='before', max_length=6),
        ),
    ]
